Java02. ДЗ 02, Голованов Сергей
GolovanovSrg/Java-2 pull request #2
Opened 2016-09-27 21:06 UTC by GolovanovSrg

@jzuken

2016-10-02 13:47 UTC, jzuken requested changes

2016-10-02 13:47 UTC, jzuken commented on VCS/pom.xml
> +<project xmlns="http://maven.apache.org/POM/4.0.0"
раз оно обрабатывает по команде за раз, хорошо бы сюда ещё какой-нибудь плагинчик, который jar собирает

2016-10-02 13:47 UTC, jzuken commented on VCS/src/main/java/ru/spbau/mit/VCS.java
> +public class VCS {
у этой штуки хорошо бы иметь публичный интерфейс, как у утилиты в целом. ну потому как кому-то может захотеться программно эту функциональность запускать

2016-10-02 13:47 UTC, jzuken commented on VCS/src/main/java/ru/spbau/mit/Info.java
> +    public static final String VCS_DIR_NAME = ".vcs";
не люблю я такие классы, когда константы отрываются от того места, где реализована эта функциональность. лучше уж их в какие-то более адекватные места перенести

2016-10-02 13:47 UTC, jzuken commented on VCS/src/main/java/ru/spbau/mit/Configuration.java
> +public class Configuration implements Serializable {
сильно не хватает джавадоков к классам с описанием их назначения и связей с другими классами и к методам

2016-10-02 13:47 UTC, jzuken commented on VCS/src/main/java/ru/spbau/mit/commands/AddCmd.java
> +            System.out.println("can not add " + path.toString());
ну а почему can not add не надо сказать?

2016-10-02 13:47 UTC, jzuken commented on VCS/src/main/java/ru/spbau/mit/commands/AddCmd.java
> +            return;
вот просто сразу return, вообще без пояснений?

2016-10-02 13:47 UTC, jzuken commented on VCS/src/main/java/ru/spbau/mit/commands/AddCmd.java
> +            System.out.println("can not add " + path.toString());
я так понимаю, это ко всем случаям обработки ошибок замечание

2016-10-02 13:47 UTC, jzuken commented on VCS/src/main/java/ru/spbau/mit/commands/CheckoutCmd.java
> +    public void execute() {
стоит избегать методов больше, чем пол-экрана, их сложно читать и понимать. лучше выносить функциональность в дополнительные методы

2016-10-02 13:47 UTC, jzuken commented
ещё тестов тут не нашёл

2016-10-02 14:11 UTC, GolovanovSrg commented on VCS/src/main/java/ru/spbau/mit/VCS.java
> +public class VCS {
@jzuken, а как же метод run, публичный...

2016-10-02 14:13 UTC, GolovanovSrg commented on VCS/src/main/java/ru/spbau/mit/Info.java
> +    public static final String VCS_DIR_NAME = ".vcs";
@jzuken, много где использую эти константы. В каждом классе свои делать?

2016-10-02 14:16 UTC, GolovanovSrg commented on VCS/src/main/java/ru/spbau/mit/Configuration.java
> +public class Configuration implements Serializable {
@jzuken, абсолютно согласен с этим замечанием, в отличие от software designа, здесь они нужны. Но если писать комментарии, вряд ли я успею к дэдлайну. Поэтому в следующей версии их тоже не будет =(.

2016-10-02 14:17 UTC, GolovanovSrg commented on VCS/src/main/java/ru/spbau/mit/commands/AddCmd.java
> +            System.out.println("can not add " + path.toString());
@jzuken, очень задолбали эти исключения и я забил =(

2016-10-02 15:28 UTC, GolovanovSrg commented on VCS/src/main/java/ru/spbau/mit/Configuration.java
> +public class Configuration implements Serializable {
А может и будут

2016-10-03 10:47 UTC, GolovanovSrg commented
Тесты и комментарии будут позже. Сборка мусора в репозитории ручная.

2016-10-22 19:15 UTC, jzuken commented on VCS/src/main/java/ru/spbau/mit/VCS.java
> +public class VCS {
я имел в виду интерфейс, повторяющий команды. чтобы кто-то мог её из своего кода подёргать, а не передавать ей просто список строк

2016-10-22 19:15 UTC, jzuken commented on VCS/src/main/java/ru/spbau/mit/commands/AddCmd.java
> +            System.out.println("can not add " + path.toString());
вот это очень печально. вы свои проблемы на пользователей перекладываете, они этого не заслужили ничем

2016-10-22 19:50 UTC, jzuken requested changes

2016-10-22 19:50 UTC, jzuken commented on VCS/src/main/java/ru/spbau/mit/Utils.java
> +public class Utils {
крутой класс утилит, которые нигде не используются :)

2016-10-22 19:50 UTC, jzuken commented on VCS/src/main/java/ru/spbau/mit/Repository.java
> +     * @throws IOException
обычно пишут, что и при каких обстоятельствах кидается

2016-10-22 19:50 UTC, jzuken commented on VCS/src/main/java/ru/spbau/mit/CommitRef.java
> + * The class is reference to a commit
ок, референс. и зачем он нужен?

2016-10-22 19:50 UTC, jzuken commented on VCS/src/main/java/ru/spbau/mit/CommitRef.java
> +        if (other instanceof CommitRef) {
ещё на равенство this обычно сравнивают вначале

2016-10-22 19:50 UTC, jzuken commented on VCS/src/main/java/ru/spbau/mit/Branch.java
> +        CommitRef newCommitRef = new CommitRef(newCommit.getId(), Arrays.asList(lastCommit));
локальные переменные newCommitRef тут можно спокойной убрать

2016-10-22 19:50 UTC, jzuken commented on VCS/src/main/java/ru/spbau/mit/CommitRef.java
> +    public boolean equals(Object other) {
а @Overrive не надо типа?

2016-10-22 19:50 UTC, jzuken commented on VCS/src/main/java/ru/spbau/mit/Branch.java
> + * The Branch
эпично. и абсолютно бессмысленно

2016-10-22 19:50 UTC, jzuken commented on VCS/src/main/java/ru/spbau/mit/commands/BranchCmd.java
> +    private boolean delete = false;
toDelete тогда уж

2016-10-22 19:50 UTC, jzuken commented on VCS/src/main/java/ru/spbau/mit/commands/BranchCmd.java
> +    private List<String> nameParam = null;
branchName?

2016-10-22 19:50 UTC, jzuken commented on VCS/src/main/java/ru/spbau/mit/commands/CommitCmd.java
> +            String message = messageParam == null ? "" : messageParam.get(0);
а он может быть не null, но при этом пустым?

2016-10-22 19:50 UTC, jzuken commented on VCS/src/main/java/ru/spbau/mit/commands/MergeCmd.java
> +        Commit childCommit= child.getCommit();
пробел

2016-10-22 19:50 UTC, jzuken commented on VCS/src/main/java/ru/spbau/mit/commands/MergeCmd.java
> +    public void execute() {
слишком большой метод, разбить его стоит

2016-10-22 19:50 UTC, jzuken commented on VCS/src/main/java/ru/spbau/mit/commands/MergeCmd.java
> +            System.out.println("Can not load configuration (" + e.getMessage() + " )");
ок, а если консоли нет? например, этот ваш код кто-то решит поиспользовать, чтобы графический клиент написать

2016-10-22 19:50 UTC, jzuken commented on VCS/src/test/ru/spbau/mit/RepositoryTest.java
> +    public void filterRepoFiles() throws Exception {
тесты это хорошо. только вот где проверяется код, который внутри команд?

2016-10-22 19:53 UTC, GolovanovSrg commented on VCS/src/main/java/ru/spbau/mit/Utils.java
> +public class Utils {
@jzuken, забыл удалить

2016-10-22 19:54 UTC, GolovanovSrg commented on VCS/src/main/java/ru/spbau/mit/CommitRef.java
> + * The class is reference to a commit
@jzuken, чтобы не хранить все коммиты с их содержимым в памяти

2016-10-22 19:56 UTC, GolovanovSrg commented on VCS/src/main/java/ru/spbau/mit/Branch.java
> + * The Branch
@jzuken, структура класса проста и понятна. Что здесь комментировать, я не знаю.

2016-10-22 19:58 UTC, GolovanovSrg commented on VCS/src/main/java/ru/spbau/mit/commands/MergeCmd.java
> +            System.out.println("Can not load configuration (" + e.getMessage() + " )");
@jzuken, планировал заменить на System.err, но не успел

2016-10-22 20:01 UTC, GolovanovSrg commented on VCS/src/test/ru/spbau/mit/RepositoryTest.java
> +    public void filterRepoFiles() throws Exception {
@jzuken, я не рассчитывал, что Вы будете смотреть код в ближайшее время. Но эти тесты точно будут завтра.

2016-10-23 11:33 UTC, jzuken commented on VCS/src/main/java/ru/spbau/mit/CommitRef.java
> + * The class is reference to a commit
прекрасно. вот именно это и надо было написать в этом комментарии

2016-10-23 11:34 UTC, jzuken commented on VCS/src/main/java/ru/spbau/mit/Branch.java
> + * The Branch
кто его использует и как, например

2016-10-23 11:35 UTC, jzuken commented on VCS/src/main/java/ru/spbau/mit/commands/MergeCmd.java
> +            System.out.println("Can not load configuration (" + e.getMessage() + " )");
вообще надо бы завернуть в своё исключение и бросить дальше. клиентский код должен будет System.err вычитывать и парсить?

2016-10-23 11:36 UTC, jzuken commented on VCS/src/test/ru/spbau/mit/RepositoryTest.java
> +    public void filterRepoFiles() throws Exception {
ну да, всего 20 дней прошло с коммита, я на этот раз супер быстр :)
ничего страшного, выкладывайте тесты, как появятся. моя задача была просто указать, что их хорошо бы иметь

2016-10-26 19:59 UTC, GolovanovSrg commented
@jzuken, исправил

2016-11-02 09:58 UTC, jzuken commented
было бы круто, если бы mvn test всё же запускал тесты :)

2016-11-02 10:00 UTC, jzuken commented
а ещё у меня тесты getAllRepoFiles() и filterRepoFiles() не проходят

2016-11-02 10:04 UTC, GolovanovSrg commented
@jzuken, у меня тесты мавин запускает.

2016-11-02 10:24 UTC, jzuken commented
✗ java -jar VCS-2.jar add zshrc                                                                   13:22:07
Can not add files which in not the repository:
zshrc

файлик лежит, что я делаю не так?

2016-11-02 11:10 UTC, GolovanovSrg commented
@jzuken, все исправил

2016-11-02 14:17 UTC, jzuken commented
при добавлении файлов в следующий коммит хорошо бы показывать их в команде status. 

➜  me@faraway ~/git/au/golovanov/VCS/target/1 git:(hw2-vcs) ✗ java -jar VCS-2.jar add bashrc 
➜  me@faraway ~/git/au/golovanov/VCS/target/1 git:(hw2-vcs) ✗ java -jar VCS-2.jar status

Untracked files:
/home/me/git/au/golovanov/VCS/target/1/VCS-2.jar

2016-11-02 14:18 UTC, jzuken commented
➜  me@faraway ~/git/au/golovanov/VCS/target/1 git:(hw2-vcs) ✗ java -jar VCS-2.jar help
Unknown command. See help.
➜  me@faraway ~/git/au/golovanov/VCS/target/1 git:(hw2-vcs) ✗ java -jar VCS-2.jar --help
Unknown command. See help.

мне кажется, надо сразу печатать хелп при незнакомой команде

2016-11-02 14:20 UTC, GolovanovSrg commented
@jzuken, поддерживается только ключ -h для help

2016-11-02 14:24 UTC, GolovanovSrg commented
@jzuken, тз: status -- измененные/удаленные/недобавленные файлов. В тз нет ничего про индексированные файлы.

2016-11-02 14:26 UTC, jzuken commented
мм, ну ок

2016-11-02 14:26 UTC, jzuken commented
куда пропал четвёртый коммит? с комментом "2" который.

➜  me@faraway ~/git/au/golovanov/VCS/target/1 git:(hw2-vcs) ✗ java -jar VCS-2.jar log                                                                          17:17:40

Commit 294dab8e-cf1f-4db0-b853-f1273587b8c6
Message: 

Commit 19ed723e-7f76-466d-8b01-152159e9286f
Message: New branch: master
➜  me@faraway ~/git/au/golovanov/VCS/target/1 git:(hw2-vcs) ✗ java -jar VCS-2.jar branch  new                                                                  17:20:01
➜  me@faraway ~/git/au/golovanov/VCS/target/1 git:(hw2-vcs) ✗ java -jar VCS-2.jar checkout new                                                                 17:20:06
➜  me@faraway ~/git/au/golovanov/VCS/target/1 git:(hw2-vcs) ✗ java -jar VCS-2.jar add zshrc                                                                    17:20:23
➜  me@faraway ~/git/au/golovanov/VCS/target/1 git:(hw2-vcs) ✗ java -jar VCS-2.jar commit "2"                                                                   17:20:29
➜  me@faraway ~/git/au/golovanov/VCS/target/1 git:(hw2-vcs) ✗ java -jar VCS-2.jar log                                                                          17:20:35

Commit 3ceb862a-d03a-4bd0-bf50-58af4009cce4
Message: 2

Commit 81b502ae-bb01-482f-b4ff-c101b1b3fe83
Message: New branch: new

Commit 294dab8e-cf1f-4db0-b853-f1273587b8c6
Message: 

Commit 19ed723e-7f76-466d-8b01-152159e9286f
Message: New branch: master
➜  me@faraway ~/git/au/golovanov/VCS/target/1 git:(hw2-vcs) ✗ java -jar VCS-2.jar checkout master                                                              17:23:06
➜  me@faraway ~/git/au/golovanov/VCS/target/1 git:(hw2-vcs) ✗ java -jar VCS-2.jar log                                                                          17:23:18

Commit 294dab8e-cf1f-4db0-b853-f1273587b8c6
Message: 

Commit 19ed723e-7f76-466d-8b01-152159e9286f
Message: New branch: master
➜  me@faraway ~/git/au/golovanov/VCS/target/1 git:(hw2-vcs) ✗ java -jar VCS-2.jar merge new                                                                    17:23:20
➜  me@faraway ~/git/au/golovanov/VCS/target/1 git:(hw2-vcs) ✗ java -jar VCS-2.jar log                                                                          17:23:41

Commit 4fc82883-8e43-4530-b612-35ee4d18a895
Message: Merge with new

Commit 294dab8e-cf1f-4db0-b853-f1273587b8c6
Message: 

Commit 19ed723e-7f76-466d-8b01-152159e9286f
Message: New branch: master

2016-11-02 14:28 UTC, GolovanovSrg commented
@jzuken, после мержа отображаю только коммиты с текущей ветки. Не git же делаем, есть вольность.

2016-11-02 14:31 UTC, jzuken commented
подождите, merge по определению должен слить две ветки в одну. нельзя при этом коммиты терять

2016-11-02 14:32 UTC, GolovanovSrg commented
@jzuken, они не теряются. Вы смотрите, что был мерж и идете смотреть другие ветки =)

2016-11-02 14:35 UTC, jzuken commented
это какой-то противоестественный merge, он должен скопировать не только файлы, но и всю историю их изменения

2016-11-02 14:36 UTC, GolovanovSrg commented
@jzuken, тз: merge -- конфликты разрешайте (или не разрешайте) любым разумным способом. В тз нет ничего про историю. Есть вольность.

2016-11-02 14:39 UTC, jzuken commented
я вам только что ТЗ уточнил, раз вам так будет угодно :)

2016-11-02 14:41 UTC, GolovanovSrg commented
@jzuken, ок, будет добавлено в будущей версии. На hwproj только уточнение добавьте.

2016-11-16 16:04 UTC, GolovanovSrg commented
@jzuken, исправил

2016-11-24 16:27 UTC, merged