Java02. ДЗ 03, Голованов Сергей
GolovanovSrg/Java-2 pull request #3
Opened 2016-10-12 19:11 UTC by GolovanovSrg

@jzuken, кода не много и он, вроде, простой, поэтому комментарии я не стал писать =)

2016-11-02 16:21 UTC, jzuken requested changes

2016-11-02 16:21 UTC, jzuken commented on FTP/src/main/java/ru/spbau/mit/Client.java
> +            System.exit(0);
не надо никогда делать exit() нигде, кроме main() (и даже там не надо, впрочем, это слишком низкоуровнево)

2016-11-02 16:21 UTC, jzuken commented on FTP/src/main/java/ru/spbau/mit/Client.java
> +        int port = Integer.valueOf(args[1]);
а если ошибёмся и введём не то, всё упадёт

2016-11-02 16:21 UTC, jzuken commented on FTP/src/main/java/ru/spbau/mit/ServerImpl.java
> +    private void executeList(String path, ObjectOutputStream output) throws IOException {
давайте какие-нибудь более конкретные исключения бросать, которые будут говорить о проблеме в терминах задачи, а не библиотек java

2016-11-02 16:21 UTC, jzuken commented on FTP/src/main/java/ru/spbau/mit/ServerImpl.java
> +                System.err.println("Client " + clientAddress + " error: " + e.getMessage());
опять же, это не тут надо делать, а в main() сервера

2016-11-02 16:21 UTC, jzuken commented on FTP/src/main/java/ru/spbau/mit/Client.java
> +        } else if (cmd.length == 2 && cmd[0].equals("get")) {
предлагаю использовать Request.toString() вместо магических констант

2016-11-02 16:21 UTC, jzuken commented on FTP/src/main/java/ru/spbau/mit/Client.java
> +        } else if (cmd.length == 2 && cmd[0].equals("get")) {
или лучше даже вообще весь протокол куда-то вынести, ниже только больше этого

2016-11-16 17:02 UTC, GolovanovSrg commented on FTP/src/main/java/ru/spbau/mit/Client.java
> +        } else if (cmd.length == 2 && cmd[0].equals("get")) {
@jzuken, это работа с консолью. Request используется для передачи команды серверу.

2016-11-16 17:56 UTC, GolovanovSrg commented on FTP/src/main/java/ru/spbau/mit/Client.java
> +            System.exit(0);
@jzuken, Вы предлагаете городить кастыли для выхода из приложения только потому, что кто-то считает, что exit слишком низкоуровнево (учитывая то, что все подготовлено для выхода). Goto тоже нельзя использовать, но только я не видел в ядре linux тонны повторяющихся строк кода.

2016-11-16 20:33 UTC, jzuken commented on FTP/src/main/java/ru/spbau/mit/Client.java
> +            System.exit(0);
Я не очень понял, причём тут goto и ядро линукса? Всё, что я сказал -- что вызывать exit() напрямую (то есть делать несколько точек выхода из программы) -- признак плохого ОО-дизайна. Вы с этим не согласны?

2016-11-16 20:33 UTC, jzuken commented on FTP/src/main/java/ru/spbau/mit/Client.java
> +        } else if (cmd.length == 2 && cmd[0].equals("get")) {
ок, но это не отменяет проблему магических констант

2016-11-16 20:54 UTC, GolovanovSrg commented on FTP/src/main/java/ru/spbau/mit/ServerImpl.java
> +                System.err.println("Client " + clientAddress + " error: " + e.getMessage());
@jzuken, я эту функцию в новый поток загоняю. Она не может кидать исключений. Вы предлагаете мне городить костыли, чтобы напечатать сообщение в main?

2016-11-16 22:05 UTC, GolovanovSrg commented on FTP/src/main/java/ru/spbau/mit/Client.java
> +            System.exit(0);
@jzuken, в данном случае не согласен. Мой посыл был в том, что если использовать exit осторожно и явно, то все будет хорошо.

2016-11-17 00:04 UTC, GolovanovSrg commented
@jzuken, все исправил

2016-11-24 17:22 UTC, jzuken commented on FTP/src/main/java/ru/spbau/mit/Client.java
> +            System.exit(0);
ну да, отличный дизайн. и к консоль писать сообщения об ошибках тоже.

2016-11-24 17:25 UTC, jzuken commented on FTP/src/main/java/ru/spbau/mit/ServerImpl.java
> +                System.err.println("Client " + clientAddress + " error: " + e.getMessage());
ну то есть вы предлагаете свою техническую задачу на неудобство пользователя переложить, правильно я понял? ещё раз -- если кто-то захочет этот код использовать в своём приложении, ему тоже консоль парсить?

2016-11-24 17:35 UTC, GolovanovSrg commented on FTP/src/main/java/ru/spbau/mit/ServerImpl.java
> +                System.err.println("Client " + clientAddress + " error: " + e.getMessage());
@jzuken, как мне получить исключение из другого потока? Просто скажите, и я сделаю.

2016-11-24 17:47 UTC, GolovanovSrg commented on FTP/src/main/java/ru/spbau/mit/ServerImpl.java
> +                System.err.println("Client " + clientAddress + " error: " + e.getMessage());
@jzuken, если я брошу RuntimeException, Вас это устроит?

2016-11-24 18:35 UTC, jzuken commented on FTP/src/main/java/ru/spbau/mit/ServerImpl.java
> +                System.err.println("Client " + clientAddress + " error: " + e.getMessage());
Thread.setDefaultUncaughtExceptionHandler() чем не подходит?

2016-11-24 20:10 UTC, GolovanovSrg commented
@jzuken, исправил

2016-11-24 20:10 UTC, GolovanovSrg commented on FTP/src/main/java/ru/spbau/mit/ServerImpl.java
> +                System.err.println("Client " + clientAddress + " error: " + e.getMessage());
@jzuken, тем, что я не знал про него.

2016-11-25 08:32 UTC, jzuken commented on FTP/src/main/java/ru/spbau/mit/Server.java
> +            ;
оригинально

2016-11-25 08:32 UTC, jzuken commented
ок, последнее замечание -- давайте добавим в мавен плагин для сборки jar'ов клиента и сервера со всеми зависимостями

2016-11-26 11:28 UTC, GolovanovSrg commented
@jzuken

2016-12-09 07:41 UTC, merged